config/routes.rb
Rails.application.routes.draw do
  get 'searches/index'
  post '/search', to: 'searches#search'
  get 'analytics/index'
  root 'searches#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/search.rb
class Search < ApplicationRecord
  belongs_to :user

  validates :query, presence: true, length: { minimum: 5 }
end

app/models/user.rb
class User < ApplicationRecord
    has_many :searches
end

app/controllers/analytics_controller.rb
class AnalyticsController < ApplicationController
  def index
    @search_queries = Search.group(:query).count
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception

  def current_user
    User.first
  end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  def index
    @search_history = current_user.searches.order("created_at DESC").limit(5)
  end

  def search
    query = params[:query].strip
  
    if query.present?
      current_user.searches.create(query: query)
    end
  
    @search_results = ["Result 1", "Result 2", "Result 3"]
  
    render json: { results: @search_results }
  end
end

app/helpers/analytics_helper.rb
module AnalyticsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/analytics/index.html.erb
<h3>Search Analytics:</h3>
<table>
  <thead>
    <tr>
      <th>Search Query</th>
      <th>Count</th>
    </tr>
  </thead>
  <tbody>
    <% @search_queries.each do |query, count| %>
      <tr>
        <td><%= query %></td>
        <td><%= count %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SearchAnalytics</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= javascript_include_tag 'search' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/searches/index.html.erb
<div>
  <input type="text" id="search-box" placeholder="Type your search">
</div>

<div>
  <h3>Search History:</h3>
  <% @search_history.each do |history| %>
    <p><%= history.query %></p>
  <% end %>
</div>

<%= link_to 'Go to Analytics', analytics_index_path %>